// data
export const SET_MANAGER = 'SET_MANAGER';

// player
export const SET_VOLUME = 'SET_VOLUME';
export const SET_SEEK_BY_PERCENT = 'SET_SEEK_BY_PERCENT';
export const SET_SEEK_BY_SECONDS = 'SET_SEEK_BY_SECONDS';
export const SET_SEEK_BY_DELTA = 'SET_SEEK_BY_DELTA';
export const RESOLVE_SEEK = 'RESOLVE_SEEK';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_CURRENT_TRACKLIST = 'SET_CURRENT_TRACKLIST';
export const SET_CURRENT_BROWSER = 'SET_CURRENT_BROWSER';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_IS_SHUFFLE = 'SET_IS_SHUFFLE';
export const SET_IS_REPEAT = 'SET_IS_REPEAT';
export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING';
export const TOGGLE_IS_SHUFFLE = 'TOGGLE_IS_SHUFFLE';
export const TOGGLE_IS_REPEAT = 'TOGGLE_IS_REPEAT';
export const SEEK_NEXT_TRACK = 'SEEK_NEXT_TRACK';
export const SEEK_PREV_TRACK = 'SEEK_PREV_TRACK';

// ui
export const SET_AUDIO_PROGRESS_DISPLAY = 'SET_AUDIO_PROGRESS_DISPLAY';
export const TOGGLE_COLLAPSE_ROOT = 'TOGGLE_COLLAPSE_ROOT';
export const TOGGLE_COLLAPSE_HEADER = 'TOGGLE_COLLAPSE_HEADER';
export const TOGGLE_COLLAPSE_SIDEBAR = 'TOGGLE_COLLAPSE_SIDEBAR';
export const TOGGLE_POPUP_ABOUT = 'TOGGLE_POPUP_ABOUT';
export const TOGGLE_POPUP_IMAGE = 'TOGGLE_POPUP_IMAGE';
export const TOGGLE_POPUP_SEARCH = 'TOGGLE_POPUP_SEARCH';
