export const SET_MANAGER = 'SET_MANAGER';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_CURRENT_TRACKLIST = 'SET_CURRENT_TRACKLIST';
export const SET_CURRENT_BROWSER = 'SET_CURRENT_BROWSER';
export const TOGGLE_COLLAPSE_ROOT = 'TOGGLE_COLLAPSE_ROOT';
export const TOGGLE_COLLAPSE_HEADER = 'TOGGLE_COLLAPSE_HEADER';
export const TOGGLE_COLLAPSE_SIDEBAR = 'TOGGLE_COLLAPSE_SIDEBAR';
